# Generated by Django 3.0.6 on 2020-05-31 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200530_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='created_on',
            new_name='created_at',
        ),
    ]
