# Generated by Django 3.0.6 on 2020-06-07 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blog_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='auth_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.User', to_field='username'),
            preserve_default=False,
        ),
    ]
