# Generated by Django 3.0.6 on 2020-06-07 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200607_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='auth_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_name', to='blog.User', to_field='username'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='blog.User'),
        ),
    ]
